gems: [
  jekyll-paginate, # 分页插件
  jekyll-sitemap   # 站点地图插件
]

title: 大连保胜装饰装修工程有限公司
address: 辽宁省大连市龙江路36号孙家沟市场对面
phone: 18604265197
contactor: 孙经理
lat: 38.890286
lng: 121.565373
#分页每页5个数据
paginate: 5
paginate_path: "blog/page:num"


keywords: "保胜装饰装修,商业场所居家酒店室内外装饰装修,大连酒店装饰装修"
description: > # this means to ignore newlines until "baseurl:"
  大连保胜装饰装修工程有限公司，主要经营各商业场所居家酒店室内外装饰装修，公司团队有十余年装修经验，曾为固特异轮胎、新雅快捷酒店等做过店面装修。
  我公司的办公地址位于中国辽宁省的一个重要沿海港口城市，
  省内第二大城市--大连，龙江路36号孙家沟市场对面，
  我们有最专业的设计师和施工团队，在公司发展壮大的过程中，
  我们为客户提供最好的装修、良好的技术服务、健全的售后服务，
  大连保胜装饰装修工程有限公司是大连建筑装修施工行业知名企业，
  如果您对我公司的服务有兴趣，请来电咨询。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dlbszszx.com"
# Build settings
markdown: kramdown

#代码高亮
highlight: true
#SASS添加
sass:
  style: compressed
